version: "3"

services:
  traefik:
    image: bearstech/traefik-dev:1.7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - janus
      - web
    ports:
      - 80:80

  janus:
    image: janus
    labels:
      traefik.http.port: "8088"
      traefik.http.frontend.rule: Host:${DOMAIN};Path:/janus
      traefik.ws.port: "8188"
      traefik.ws.frontend.rule: Host:${DOMAIN};Headers:Upgrade,websocket
    environment:
      PUBLIC_IP: "${PUBLIC_IP}"
      TURN_USER: "${TURN_USER}"
      TURN_CREDENTIAL: "${TURN_CREDENTIAL}"
    restart: always

  web:
    image: bearstech/nginx
    volumes:
      - ./web:/var/www/html
      - ./nginx.conf:/etc/nginx/sites-enabled/default
    labels:
      traefik.frontend.rule: Host:${DOMAIN}
