version: "3"

services:
  traefik:
    image: bearstech/traefik-dev:1.7
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - janus
      - web
    ports:
      - 80:80

  janus:
    image: janus
    labels:
      - traefik.http.port=8088
      - traefik.http.frontend.rule=Host:localhost;Path:/janus
      - traefik.ws.port=8188
      - traefik.ws.frontend.rule=Host:localhost;Headers:Upgrade,websocket

  web:
    image: bearstech/nginx
    volumes:
      - ./web:/var/www/html
    labels:
      - traefik.frontend.rule=Host:localhost