FROM bearstech/debian:buster

RUN set -eux \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        gettext-base \
        libjs-janus \
        janus \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/*

ARG UID=1001
RUN useradd janus --uid ${UID} --shell /bin/bash --system

# http
EXPOSE 8088
# ws
EXPOSE 8188
# admin
EXPOSE 7088

COPY etc/janus /etc/janus
USER janus

CMD ["janus"]