FROM bearstech/debian:buster

RUN set -eux \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
        ca-certificates \
        gettext-base \
        libjs-janus \
        janus \
    &&  apt-get clean \
    &&  rm -rf /var/lib/apt/lists/*

ARG UID=1001
RUN useradd janus --uid ${UID} --shell /bin/bash --system

# http
EXPOSE 8088
# ws
EXPOSE 8188
# admin
EXPOSE 7088

COPY entrypoint.sh /entrypoint.sh
COPY --chown=janus etc/janus /etc/janus
RUN touch /etc/janus/janus.jcfg && chmod 666 /etc/janus/janus.jcfg
USER janus

ENTRYPOINT ["/entrypoint.sh"]
CMD ["janus"]